"use client";
// app/lookup/page.tsx — Feature 2: Stock Lookup & Analysis
import { useState, useEffect, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useSession } from "next-auth/react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Search,
  AlertCircle,
  BookOpen,
  FileText,
  Newspaper,
  Info,
  ExternalLink,
  LogIn,
} from "lucide-react";
import SearchBar from "@/components/SearchBar";
import StockHeader from "@/components/StockHeader";
import ValuationGauge from "@/components/ValuationGauge";
import NewsCard, { NewsItem } from "@/components/NewsCard";
import { StockData } from "@/lib/financeApi";
import { METRIC_CONFIGS } from "@/lib/valuationBands";
import { generateValuationSummary } from "@/lib/valuationSummary";
import Link from "next/link";

// ─── Skeleton loader ──────────────────────────────────────────────────────────
function Skeleton({ className = "" }: { className?: string }) {
  return <div className={`animate-pulse rounded-lg bg-gray-200 dark:bg-gray-800 ${className}`} />;
}

function StockSkeleton() {
  return (
    <div className="space-y-6 mt-6">
      <Skeleton className="h-40 w-full rounded-2xl" />
      <div className="grid sm:grid-cols-3 gap-4">
        <Skeleton className="h-40 rounded-2xl" />
        <Skeleton className="h-40 rounded-2xl" />
        <Skeleton className="h-40 rounded-2xl" />
      </div>
      <Skeleton className="h-28 rounded-2xl" />
      <div className="space-y-3">
        <Skeleton className="h-20 rounded-xl" />
        <Skeleton className="h-20 rounded-xl" />
        <Skeleton className="h-20 rounded-xl" />
      </div>
    </div>
  );
}

// ─── Metric sub-panel ────────────────────────────────────────────────────────
function MetricPanel({
  label,
  shortId,
  value,
  helpText,
}: {
  label:    string;
  shortId:  "pe" | "forwardPe" | "peg";
  value:    number | null;
  helpText: string;
}) {
  const metricConfig = METRIC_CONFIGS.find((m) => m.id === shortId)!;

  return (
    <div className="p-5 rounded-2xl border border-gray-200 dark:border-gray-700/60 bg-white dark:bg-gray-900 space-y-4">
      <div className="flex items-start justify-between gap-2">
        <div>
          <h3 className="font-bold text-gray-900 dark:text-white text-sm">{label}</h3>
          <p className="text-xs text-gray-400 dark:text-gray-500 mt-0.5">{helpText}</p>
        </div>
        {value != null ? (
          <span className="text-2xl font-extrabold text-gray-900 dark:text-white tabular-nums">
            {value.toFixed(shortId === "peg" ? 2 : 1)}×
          </span>
        ) : (
          <span className="text-sm text-gray-400 dark:text-gray-500 italic">N/A</span>
        )}
      </div>
      <ValuationGauge metricId={shortId} value={value ?? undefined} size="sm" showValue />
      <Link
        href={`/learn#${shortId}`}
        className="inline-flex items-center gap-1 text-xs text-indigo-500 hover:text-indigo-700 dark:hover:text-indigo-300 transition-colors"
      >
        <BookOpen className="w-3 h-3" />
        What is {metricConfig.shortName}?
      </Link>
    </div>
  );
}

// ─── Valuation summary panel ─────────────────────────────────────────────────
function ValuationSummary({ data }: { data: StockData }) {
  const summary = generateValuationSummary({
    ticker:     data.ticker,
    name:       data.name,
    peTrailing: data.peTrailing,
    peForward:  data.peForward,
    peg:        data.peg,
    sector:     data.sector,
  });

  return (
    <div className="p-5 rounded-2xl border border-indigo-200 dark:border-indigo-800/50 bg-indigo-50 dark:bg-indigo-950/30 space-y-3">
      <div className="flex items-center gap-2">
        <FileText className="w-4 h-4 text-indigo-600 dark:text-indigo-400 shrink-0" />
        <h3 className="font-bold text-gray-900 dark:text-white text-sm">
          Auto-Generated Valuation Summary
        </h3>
        <span className="ml-auto text-xs px-2 py-0.5 rounded-full bg-indigo-100 dark:bg-indigo-900/50 text-indigo-600 dark:text-indigo-400 font-medium">
          Rule-based · Not AI
        </span>
      </div>
      <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">{summary}</p>
      <p className="text-xs text-indigo-500 dark:text-indigo-400 italic flex items-start gap-1">
        <Info className="w-3 h-3 mt-0.5 shrink-0" />
        This summary is generated by deterministic rules — not a language model. It reflects where
        each metric falls in standard valuation ranges and is provided for educational purposes only.
      </p>
    </div>
  );
}

// ─── News section ────────────────────────────────────────────────────────────
interface NewsData {
  earningsNews: NewsItem[];
  regularNews:  NewsItem[];
}

function NewsSection({ ticker }: { ticker: string }) {
  const [news,    setNews]    = useState<NewsData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error,   setError]   = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    fetch(`/api/news/${encodeURIComponent(ticker)}`)
      .then((r) => r.json())
      .then((d) => {
        if (d.error) throw new Error(d.error);
        setNews(d);
      })
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, [ticker]);

  if (loading) {
    return (
      <div className="space-y-3">
        {Array.from({ length: 4 }).map((_, i) => (
          <Skeleton key={i} className="h-20 rounded-xl" />
        ))}
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center gap-2 p-4 rounded-xl bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800/50 text-sm text-amber-700 dark:text-amber-400">
        <AlertCircle className="w-4 h-4 shrink-0" />
        News could not be loaded: {error}
      </div>
    );
  }

  const allEmpty = !news?.earningsNews.length && !news?.regularNews.length;

  return (
    <div className="space-y-6">
      {/* Earnings / guidance news */}
      {(news?.earningsNews?.length ?? 0) > 0 && (
        <div>
          <h3 className="font-bold text-gray-900 dark:text-white text-sm mb-3 flex items-center gap-2">
            <span className="inline-flex items-center px-2 py-0.5 rounded-full bg-amber-100 dark:bg-amber-900/40 text-amber-700 dark:text-amber-400 text-xs font-semibold">
              Latest Earnings Commentary
            </span>
          </h3>
          <div className="space-y-3">
            {news!.earningsNews.map((item) => (
              <NewsCard key={item.id} item={item} variant="earnings" />
            ))}
          </div>
          <p className="text-xs text-gray-400 dark:text-gray-500 mt-2 flex items-center gap-1">
            <ExternalLink className="w-3 h-3" />
            These are news headlines only — click each to read the full article at the original source.
          </p>
        </div>
      )}

      {/* Regular news */}
      {(news?.regularNews?.length ?? 0) > 0 && (
        <div>
          <h3 className="font-bold text-gray-900 dark:text-white text-sm mb-3 flex items-center gap-2">
            <Newspaper className="w-4 h-4 text-gray-400" />
            Recent News
          </h3>
          <div className="space-y-3">
            {news!.regularNews.map((item) => (
              <NewsCard key={item.id} item={item} variant="regular" />
            ))}
          </div>
        </div>
      )}

      {allEmpty && (
        <p className="text-sm text-gray-400 dark:text-gray-500 italic text-center py-6">
          No recent news found for {ticker}.
        </p>
      )}
    </div>
  );
}

// ─── Data source badge ───────────────────────────────────────────────────────
function SourceBadge({ source }: { source: string }) {
  return (
    <span className="text-xs text-gray-400 dark:text-gray-500 flex items-center gap-1">
      <Info className="w-3 h-3" />
      Data: {source}
    </span>
  );
}

// ─── Error state ─────────────────────────────────────────────────────────────
function ErrorState({ message, ticker }: { message: string; ticker: string }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      className="mt-8 flex flex-col items-center text-center gap-4 py-16"
    >
      <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-red-50 dark:bg-red-950/40">
        <AlertCircle className="w-8 h-8 text-red-500" />
      </div>
      <div>
        <h3 className="font-bold text-gray-900 dark:text-white text-lg mb-1">
          Could not load &quot;{ticker}&quot;
        </h3>
        <p className="text-sm text-gray-500 dark:text-gray-400 max-w-md">{message}</p>
        <p className="text-sm text-gray-400 dark:text-gray-500 mt-2">
          Try a valid U.S. ticker, e.g.{" "}
          {["AAPL", "MSFT", "TSLA"].map((t) => (
            <a
              key={t}
              href={`/lookup?ticker=${t}`}
              className="text-indigo-500 hover:underline mx-1"
            >
              {t}
            </a>
          ))}
        </p>
      </div>
    </motion.div>
  );
}

// ─── Main page content (needs Suspense for useSearchParams) ──────────────────
function LookupContent() {
  const searchParams          = useSearchParams();
  const router                = useRouter();
  const { status }            = useSession();
  const [ticker,    setTicker]    = useState(searchParams.get("ticker") ?? "");
  const [stockData, setStockData] = useState<StockData | null>(null);
  const [loading,   setLoading]   = useState(false);
  const [error,     setError]     = useState<string | null>(null);

  // Load stock when ticker param changes
  useEffect(() => {
    const t = searchParams.get("ticker");
    if (!t) return;
    setTicker(t);
    loadStock(t);
  }, [searchParams]);

  async function loadStock(sym: string) {
    const clean = sym.trim().toUpperCase();
    if (!clean) return;
    setLoading(true);
    setError(null);
    setStockData(null);
    try {
      const res  = await fetch(`/api/stock/${encodeURIComponent(clean)}`);
      const data = await res.json();
      if (!res.ok || data.error) throw new Error(data.error ?? "Unknown error");
      setStockData(data);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Failed to load stock data.");
    } finally {
      setLoading(false);
    }
  }

  function handleSelect(sym: string) {
    const clean = sym.toUpperCase();
    setTicker(clean);
    router.push(`/lookup?ticker=${encodeURIComponent(clean)}`);
  }

  return (
    <div className="min-h-[calc(100vh-4rem)]">
      {/* Page header */}
      <section className="px-4 py-12 bg-gradient-to-b from-violet-50 to-white dark:from-violet-950/30 dark:to-gray-950 border-b border-gray-200 dark:border-gray-800">
        <div className="max-w-3xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-violet-100 dark:bg-violet-950/60 border border-violet-200 dark:border-violet-800 text-violet-700 dark:text-violet-300 text-xs font-semibold mb-5">
            <Search className="w-3.5 h-3.5" />
            Stock Lookup
          </div>
          <h1 className="text-4xl sm:text-5xl font-extrabold text-gray-900 dark:text-white tracking-tight mb-4">
            Analyze any stock
          </h1>
          <p className="text-base text-gray-500 dark:text-gray-400 max-w-xl mx-auto mb-8">
            Search a U.S. ticker to see live P/E, Forward P/E, and PEG ratios — with a
            plain-language valuation summary and the latest news.
          </p>
          {/* Auth gate banner — shown before they try to search */}
          {status === "unauthenticated" && (
            <div className="max-w-xl mx-auto mb-5 flex items-center justify-between gap-3 px-4 py-3 rounded-xl bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800/50 text-sm">
              <span className="text-amber-700 dark:text-amber-300 font-medium text-left">
                Sign in to search stocks.
              </span>
              <Link
                href="/login?callbackUrl=/lookup"
                className="shrink-0 inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold transition-colors"
              >
                <LogIn className="w-3 h-3" />
                Sign In
              </Link>
            </div>
          )}
          <SearchBar
            initialValue={ticker}
            onSelect={handleSelect}
            className="max-w-xl mx-auto"
            autoFocus
          />
        </div>
      </section>

      {/* Results */}
      <div className="max-w-3xl mx-auto px-4 pb-20">
        {loading && <StockSkeleton />}

        {error && !loading && (
          <ErrorState message={error} ticker={ticker} />
        )}

        <AnimatePresence mode="wait">
          {stockData && !loading && (
            <motion.div
              key={stockData.ticker}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.4 }}
              className="mt-6 space-y-6"
            >
              {/* Header card */}
              <StockHeader data={stockData} />

              {/* Metrics panel */}
              <div>
                <h2 className="text-sm font-bold text-gray-900 dark:text-white mb-3 flex items-center justify-between">
                  <span>Valuation Metrics</span>
                  <SourceBadge source={`${stockData.sources.metrics} (via ${stockData.sources.quote})`} />
                </h2>
                <div className="grid sm:grid-cols-3 gap-4">
                  <MetricPanel
                    label="Trailing P/E"
                    shortId="pe"
                    value={stockData.peTrailing}
                    helpText="Share Price ÷ EPS (last 12m)"
                  />
                  <MetricPanel
                    label="Forward P/E"
                    shortId="forwardPe"
                    value={stockData.peForward}
                    helpText="Price ÷ Estimated EPS (next 12m)"
                  />
                  <MetricPanel
                    label="PEG Ratio"
                    shortId="peg"
                    value={stockData.peg}
                    helpText="P/E ÷ Expected EPS Growth Rate"
                  />
                </div>

                {/* Forward vs Trailing signal */}
                {stockData.peTrailing != null && stockData.peForward != null && (
                  <div className="mt-3 px-4 py-3 rounded-xl bg-blue-50 dark:bg-blue-950/30 border border-blue-200 dark:border-blue-800/50 text-xs text-blue-800 dark:text-blue-300 flex items-start gap-2">
                    <span className="shrink-0">💡</span>
                    <span>
                      <strong>Trailing vs Forward signal: </strong>
                      {stockData.peTrailing > stockData.peForward
                        ? `Forward P/E (${stockData.peForward.toFixed(1)}×) < Trailing P/E (${stockData.peTrailing.toFixed(1)}×) — analysts expect earnings to grow.`
                        : stockData.peForward > stockData.peTrailing
                        ? `Forward P/E (${stockData.peForward.toFixed(1)}×) > Trailing P/E (${stockData.peTrailing.toFixed(1)}×) — analysts expect earnings to decline. Watch closely.`
                        : "Forward and trailing P/E are roughly equal — flat earnings expectations."}
                    </span>
                  </div>
                )}
              </div>

              {/* Valuation summary */}
              <ValuationSummary data={stockData} />

              {/* News */}
              <div>
                <h2 className="text-sm font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2">
                  <Newspaper className="w-4 h-4 text-gray-400" />
                  News &amp; Earnings Commentary
                </h2>
                <NewsSection ticker={stockData.ticker} />
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Empty state */}
        {!loading && !error && !stockData && (
          <div className="text-center py-20 text-gray-400 dark:text-gray-600">
            <Search className="w-12 h-12 mx-auto mb-4 opacity-30" />
            <p className="text-base font-medium">Search for a ticker above to begin.</p>
            <p className="text-sm mt-1">Try AAPL, MSFT, TSLA, NVDA, or any U.S. stock symbol.</p>
          </div>
        )}

        {/* 401 gate — show friendly sign-in prompt when API returns 401 */}
        {error?.includes("Sign in") && (
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            className="mt-8 flex flex-col items-center text-center gap-4 py-16"
          >
            <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-indigo-50 dark:bg-indigo-950/40">
              <LogIn className="w-8 h-8 text-indigo-500" />
            </div>
            <div>
              <h3 className="font-bold text-gray-900 dark:text-white text-lg mb-1">
                Sign in to use Stock Lookup
              </h3>
              <p className="text-sm text-gray-500 dark:text-gray-400 max-w-sm">
                Create a free account or sign in to search any U.S. ticker and view live valuation metrics.
              </p>
            </div>
            <Link
              href="/login?callbackUrl=/lookup"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-sm transition-colors shadow-sm"
            >
              <LogIn className="w-4 h-4" />
              Sign In or Create Account
            </Link>
          </motion.div>
        )}
      </div>
    </div>
  );
}

// ─── Page export (wrapped in Suspense for useSearchParams) ───────────────────
export default function LookupPage() {
  return (
    <Suspense
      fallback={
        <div className="max-w-3xl mx-auto px-4 pt-20">
          <StockSkeleton />
        </div>
      }
    >
      <LookupContent />
    </Suspense>
  );
}
